import { Environment } from './environment.interface';

// ── Environnement LOCAL ───────────────────────────────────────
// Démarrage : npm run start:local
// Backend   : http://localhost:8083 via proxy Angular (/v1 → localhost:8083)
export const environment: Environment = {
  name: 'local',
  production: false,
  debug: true,
  apiUrl: 'http://localhost:8083',
  proxyEnabled: true,
  appName: 'KMS — Crypto Key Manager',
  bearerToken: 'eyJraWQiOiJxZVFUVWp0TzZUaTFXZTUtVk9zWktiLTZubndGdHFxMHROQTZMbm5EbGNBIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmVIR1AtOHZXQVRCUE1lcjZKWUgwWjgtZnpKdThNdmVBdTE1SkxadjMzX0UiLCJpc3MiOiJodHRwczovL3Nzby11YXQucmVuYXVsdC5jb20vb2F1dGgyL2F1c3R3b2VzaGJDa1BKeXcxNDE2IiwiYXVkIjoiaHR0cHM6Ly9hcGlzLnJlbmF1bHQuY29tIiwiaWF0IjoxNzc4MzM1MTA1LCJleHAiOjE3NzgzMzg3MDUsImNpZCI6Imlybi03NzE1NF91YXRfY29kZV8xbmF0c255dXV1cHQiLCJ1aWQiOiIwMHU3N3kzbXNoQ2JGNWlSNTQxNyIsInNjcCI6WyJsZWdhY3kiLCJhcGlzLmRlZmF1bHQiLCJhbGxpYW5jZV9wcm9maWxlIl0sImF1dGhfdGltZSI6MTc3ODMzNTEwNCwiYXBwcm92ZXIiOiJST1VWRVVSRSBOaWNvbGFzIiwibGFzdE5hbWUiOiJFbC1NYXJkaSIsInN1YiI6InB5MTI0MzEiLCJwZXJzb25hbFVuaXF1ZUlkIjoiMDAwMEc3QVAiLCJwcmVmZXJyZWRMYW5ndWFnZSI6ImZyIiwiYXBwcm92ZXJNYWlsIjoibmljb2xhcy5yb3V2ZXVyZUByZW5hdWx0LmNvbSIsIm1haWwiOiJ5YXNzaW5lLmVsLW1hcmRpLWV4dGVybkByZW5hdWx0LmNvbSIsImlybiI6IklSTi03NzE1NCIsImRpc3BsYXlOYW1lIjoiRUwtTUFSREkgWWFzc2luZSIsImNvc3RDZW50ZXIiOiJSQjUwMDAzIiwiYXBwcm92ZXJJZCI6ImEwMDU3OTAiLCJyb2xlcyI6WyJrbXNfdXNlciJdLCJsYW5ndWFnZSI6ImZyX01BIiwibG9naW4iOiJweTEyNDMxIiwiY2VydC11aWQiOiIiLCJmaXJzdE5hbWUiOiJZYXNzaW5lIiwicG9zdE9mZmljZUJveCI6Ik1BQ0FTSFVCMTAwIiwiY291bnRyeUNvZGUiOiJNQSIsInBlcmltZXRlciI6Ik5vbmUiLCJjb21wYW55IjoiMTAwMyIsInVzZXJUeXBlIjoiQjJFX0NvbnRyYWN0b3IiLCJwZXJzb25UeXBlIjoiY2F0cHJnciJ9.Yxijag2GefzJO02wrDSwd0XvSLWTEJ6RrlQCtRul2_Zkg-ZR-eY1XDhsS5QPF6YSVrdscQPm9aymyECMmlAA9Cu88cerZ18BmwUdVfWKqE6tQ65vmIeNRNVwLNsjFusT-QDGUn3nm-vIPswlcSM2aoz0J-DoCW8RnE_v1HNW33LoZZUWjbUh0JKbhXvYt7eKi6zfh_dYC6KkApmEkVad_pAX6EqojRVmlmEZIBgKRR-AgCmV2rm5uAD8XymwEm0PV9nU5MF4bKjncZIc2fU8mRZhFHziJiacIvki-AMssJceIQMvV7UG1M2WtuHjbFSBfB-QVXID_-aJc-u6f2MWHQ',
};
